// Public MailExtension APIs only. No Experiment, shell, credentials or send API.
export function createBackend(api,config){
 const epoch=crypto.randomUUID(),cursors=new Map(),events=[];let eventId=0,writeQueue=Promise.resolve();
 const fail=(code)=>{throw Object.assign(new Error(code),{code});};
 const allowed=id=>{if(!config.accountIds.includes(id))fail('PERMISSION_DENIED');};
 const folder=async id=>{const f=await api.folders.get(id);allowed(f.accountId);return f;};
 const digest=async text=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text))),b=>b.toString(16).padStart(2,'0')).join('');
 async function summarize(m){if(!m.folder?.id)fail('EXTERNAL_MESSAGE');allowed(m.folder.accountId);const fp=await digest(JSON.stringify([m.headerMessageId,m.date,m.author,m.subject,m.size]));return {ref:{epoch,accountId:m.folder.accountId,folderId:m.folder.id,messageId:m.id,fingerprint:fp},subject:m.subject,author:m.author,recipients:m.recipients,date:m.date,size:m.size,read:m.read,flagged:m.flagged,junk:m.junk,tags:m.tags,untrustedContent:true};}
 async function resolve(ref){if(!ref||ref.epoch!==epoch)fail('STALE_REFERENCE');allowed(ref.accountId);const m=await api.messages.get(ref.messageId);const current=await summarize(m);if(current.ref.folderId!==ref.folderId||current.ref.accountId!==ref.accountId||current.ref.fingerprint!==ref.fingerprint)fail('STALE_REFERENCE');return m;}
 async function page(list,tail,limit){let entries=[...tail,...(list.messages||[])],next=list.id;
  while(entries.length<limit&&next){const continued=await api.messages.continueList(next);entries.push(...continued.messages);next=continued.id;}
  const selected=entries.splice(0,limit);let cursor=null;
  if(entries.length||next){cursor=crypto.randomUUID();if(cursors.size>=32){const [oldest,value]=cursors.entries().next().value;cursors.delete(oldest);if(value.listId)await api.messages.abortList(value.listId).catch(()=>{});}cursors.set(cursor,{tail:entries,listId:next,expires:Date.now()+300000});}
  return {messages:await Promise.all(selected.map(summarize)),cursor,epoch,coverage:'THUNDERBIRD_VISIBLE_STATE',completeServerArchive:false};
 }
 const bytesToBase64=data=>{let text='';for(let i=0;i<data.length;i+=16384)text+=String.fromCharCode(...data.subarray(i,i+16384));return btoa(text);};
 async function chunk(file,offset=0,length=131072){if(file.size>25*1024*1024)fail('MESSAGE_TOO_LARGE');if(!Number.isInteger(offset)||offset<0||offset>file.size||!Number.isInteger(length)||length<1||length>131072)fail('INVALID_PARAMETERS');const data=new Uint8Array(await file.slice(offset,offset+length).arrayBuffer());return {base64:bytesToBase64(data),offset,totalBytes:file.size,nextOffset:offset+data.length<file.size?offset+data.length:null};}
 async function identity(identityId){for(const a of await api.accounts.list()){if(config.accountIds.includes(a.id)&&a.identities.some(i=>i.id===identityId))return a.id;}fail('PERMISSION_DENIED');}
 const methods={
  async status(){const info=await api.runtime.getBrowserInfo();return {connected:true,addonVersion:api.runtime.getManifest?.().version||'unknown',protocolVersion:1,version:info.version,profileId:config.profileId,profileBinding:'installation',epoch,sendingEnabled:false,capabilities:{headers:!!api.messages.getHeaders,inlineText:!!api.messages.listInlineTextParts,events:true,contacts:!!api.addressBooks},unsupported:['send','calendar','filters','preferences','credentials','offline_profile_read']};},
  async accounts(){return (await api.accounts.list()).filter(a=>config.accountIds.includes(a.id)).map(a=>({id:a.id,name:a.name,type:a.type,identities:a.identities}));},
  async folders(p){allowed(p.accountId);return (await api.folders.query({accountId:p.accountId,isRoot:false})).filter(f=>!f.isVirtual).map(f=>({id:f.id,accountId:f.accountId,name:f.name,path:f.path,specialUse:f.specialUse,type:f.type}));},
  async folder_status(p){await folder(p.folderId);return api.folders.getFolderInfo(p.folderId);},
  async search(p){await folder(p.folderId);const q={folderId:p.folderId,includeSubFolders:false};for(const key of ['subject','author','recipients','body','flagged'])if(p[key]!==undefined)q[key]=p[key];if(p.unread!==undefined)q.read=!p.unread;if(p.fromDate)q.fromDate=new Date(p.fromDate);if(p.toDate)q.toDate=new Date(p.toDate);return page(await api.messages.query(q),[],p.limit||25);},
  async next(p){const v=cursors.get(p.cursor);if(v&&v.expires<Date.now()){cursors.delete(p.cursor);if(v.listId)await api.messages.abortList(v.listId).catch(()=>{});fail('STALE_CURSOR');}if(!v)fail('STALE_CURSOR');cursors.delete(p.cursor);return page(v.listId?await api.messages.continueList(v.listId):{messages:[]},v.tail,p.limit||25);},
  async cancel_search(p){const v=cursors.get(p.cursor);if(v?.listId)await api.messages.abortList(v.listId);cursors.delete(p.cursor);return {cancelled:true};},
  async read(p){const m=await resolve(p.ref),full=await api.messages.getFull(m.id);if(full.decryptionStatus==='fail')fail('DECRYPTION_FAILED');let text='';const walk=part=>{if(part.contentType==='text/plain'&&part.body)text+=part.body+'\n';for(const child of part.parts||[])walk(child);};walk(full);if(!text&&api.messages.listInlineTextParts){const parts=await api.messages.listInlineTextParts(m.id);for(const part of parts){if(part.contentType==='text/plain')text+=part.content+'\n';else if(part.contentType==='text/html')text+=await api.messengerUtilities.convertToPlainText(part.content)+'\n';}}
   const attachments=await api.messages.listAttachments(m.id);return {message:await summarize(m),headers:full.headers,text:text.slice(0,100000),textTruncated:text.length>100000,decryptionStatus:full.decryptionStatus||'not_reported',attachments:attachments.map(a=>({partName:a.partName,name:a.name,size:a.size,contentType:a.contentType})),untrustedContent:true};},
  async headers(p){const m=await resolve(p.ref);return {headers:api.messages.getHeaders?await api.messages.getHeaders(m.id):(await api.messages.getFull(m.id)).headers,untrustedContent:true};},
  async attachment(p){const m=await resolve(p.ref);const attachments=await api.messages.listAttachments(m.id);if(!attachments.some(a=>a.partName===p.partName))fail('ATTACHMENT_NOT_FOUND');const file=await api.messages.getAttachmentFile(m.id,p.partName);return {...await chunk(file,p.offset,p.length),untrustedContent:true};},
  async export(p){const m=await resolve(p.ref);let raw=await api.messages.getRaw(m.id,{data_format:'File',decrypt:false});if(typeof raw==='string')raw=new File([Uint8Array.from(raw,c=>c.charCodeAt(0))],'message.eml');return {...await chunk(raw,p.offset,p.length),untrustedContent:true};},
  async books(){return (await api.addressBooks.list()).filter(b=>(config.addressBookIds||[]).includes(b.id)).map(b=>({id:b.id,name:b.name,readOnly:b.readOnly,remote:b.remote}));},
  async contacts(p){const matches=[];for(const parentId of config.addressBookIds||[])matches.push(...(await api.addressBooks.contacts.query({parentId,searchString:p.query})).filter(c=>c.parentId===parentId));return {contacts:matches.slice(0,p.limit||25),truncated:matches.length>(p.limit||25),untrustedContent:true};},
  async tags(){return api.messages.tags.list();},
  async events(p){if(p.epoch&&p.epoch!==epoch)fail('STALE_REFERENCE');const batch=events.filter(e=>e.id>(p.after||0)).slice(0,100);return {epoch,events:batch,nextAfter:batch.at(-1)?.id||p.after||0,lastId:eventId,lostBefore:events[0]?.id||0};},
  async execute(p){const a=p.action;if(a.epoch!==epoch)fail('STALE_REFERENCE');
   if(a.kind==='save_draft'){await identity(a.identityId);const details={identityId:a.identityId,to:a.to,cc:a.cc||[],bcc:a.bcc||[],subject:a.subject,plainTextBody:a.body,isPlainText:true};if(a.replyRef)await resolve(a.replyRef);const tab=a.replyRef?await api.compose.beginReply(a.replyRef.messageId,'replyToSender',details):await api.compose.beginNew(details);const saved=await api.compose.saveMessage(tab.id,{mode:'draft'});return {tabId:tab.id,mode:saved.mode,messages:await Promise.all((saved.messages||[]).map(summarize)),sent:false};}
   if(a.kind==='import'){await folder(a.destination);if(typeof a.emlBase64!=='string'||a.emlBase64.length>699052||!/^([A-Za-z0-9+/]{4})*([A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(a.emlBase64))fail('INVALID_PARAMETERS');const data=Uint8Array.from(atob(a.emlBase64),c=>c.charCodeAt(0));return summarize(await api.messages.import(new File([data],'import.eml',{type:'message/rfc822'}),a.destination,{read:false}));}
   if(a.kind==='create_folder'){await folder(a.parentFolderId);if(!a.name||/[\r\n\x00/\\]/.test(a.name))fail('INVALID_PARAMETERS');return api.folders.create(a.parentFolderId,a.name);}
   // Special-folder protection prevents changing the folder itself; approved message moves into Inbox/Trash remain legitimate.
   if(['rename_folder','delete_folder'].includes(a.kind)){const f=await folder(a.folderId);if(f.isRoot||f.isVirtual||(f.specialUse||[]).length||(f.type&&f.type!=='normal'))fail('PROTECTED_FOLDER');if(a.kind==='rename_folder'&&(!a.name||a.name.length>100||/[\r\n\x00/\\]/.test(a.name)))fail('INVALID_PARAMETERS');if(a.kind==='rename_folder')return api.folders.rename(a.folderId,a.name);const info=await api.folders.getFolderInfo(a.folderId),children=await api.folders.getSubFolders(a.folderId);if(info.totalMessageCount!==0||children.length)fail('FOLDER_NOT_EMPTY');await api.folders.delete(a.folderId);return {deleted:true};}
   const m=await resolve(a.ref);
   if(a.kind==='update'){const allowedProperties=['read','flagged','junk','tags'];if(!a.properties||Object.keys(a.properties).some(k=>!allowedProperties.includes(k)))fail('INVALID_PARAMETERS');await api.messages.update(m.id,a.properties);return summarize(await api.messages.get(m.id));}
   if(a.kind==='archive'){await api.messages.archive([m.id]);return {requested:'archive',deliveryVerified:false};}
   if(['copy','move'].includes(a.kind)){await folder(a.destination);await api.messages[a.kind]([m.id],a.destination,{isUserAction:true});let sourcePresent;try{sourcePresent=(await api.messages.get(m.id)).folder.id===a.ref.folderId;}catch{sourcePresent=false;}return {requested:a.kind,destination:a.destination,sourcePresent};}
   if(a.kind==='trash'){const trash=(await api.folders.query({accountId:m.folder.accountId,specialUse:['trash']})).filter(f=>!f.isVirtual);if(trash.length!==1)fail('TRASH_FOLDER_AMBIGUOUS');if(trash[0].id===m.folder.id)fail('ALREADY_IN_TRASH');await api.messages.move([m.id],trash[0].id,{isUserAction:true});return {requested:'trash',destination:trash[0].id,deliveryVerified:false};}
   fail('UNSUPPORTED_ACTION');
  }
 };
 function event(type,data){events.push({id:++eventId,type,...data});if(events.length>1000)events.shift();}
 api.messages.onNewMailReceived?.addListener((f,m)=>{if(config.accountIds.includes(f.accountId))event('new',{folderId:f.id,count:m.messages?.length||0});});
 for(const [name,type] of [['onMoved','moved'],['onCopied','copied'],['onDeleted','deleted']])api.messages[name]?.addListener(list=>{const scoped=(list.messages||[]).filter(m=>config.accountIds.includes(m.folder?.accountId));if(scoped.length)event(type,{messageIds:scoped.map(m=>m.id),partial:!!list.id});});
 api.messages.onUpdated?.addListener(m=>{if(config.accountIds.includes(m.folder?.accountId))event('updated',{messageId:m.id,folderId:m.folder.id});});
 return {epoch,async dispatch(method,p={}){if(!Object.hasOwn(methods,method))fail('UNSUPPORTED_METHOD');if(p.limit!==undefined&&(!Number.isInteger(p.limit)||p.limit<1||p.limit>100))fail('INVALID_PARAMETERS');if(p.profileId&&p.profileId!==config.profileId)fail('PROFILE_MISMATCH');if(method==='execute'){const next=writeQueue.then(()=>methods.execute(p));writeQueue=next.catch(()=>{});return next;}return methods[method](p);}};
}
